name: LevandaUI
main: NurAzliYT\LevandaUI\LevandaUI\LevandaUI
version: 1.0.0
api: 5.0.0
author: NurAzliYT
description: "Menu For Your Server"

commands:
  levandaui:
    description: "Open LevandaUI Menu"
    permission: levandaui.ui

permissions:
  levandaui.ui:
    default: true
